// <auto-generated />
namespace ContactManager.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ContactAddImage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ContactAddImage));
        
        string IMigrationMetadata.Id
        {
            get { return "201302141255392_Contact-AddImage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
